name: stonks_series
channels:
  - msys2
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.8.13
  - pip:
    - cython
    - numpy
    - prophet
    - m2w64-toolchain
    - pystan
    - streamlit
    - plotly==5.8.2
    - yfinance==0.1.72
