name: stonks_series
channels:
  - defaults
dependencies:
  - python=3.8
  - libpython
  - m2w64-toolchain
  - numpy
  - cython
  - scipy
  - matplotlib
  - pandas
  - pystan
  - prophet
pip:
    - m2w64-toolchain
    - libpython
